In [5]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [4]:
fire=pd.read_csv("forestfires.csv")

In [6]:
#Preprocessing data
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
fire["month"] = label_encoder.fit_transform(fire["month"])
fire["day"] = label_encoder.fit_transform(fire["day"])
fire["size_category"] = label_encoder.fit_transform(fire["size_category"])


In [8]:
fire.head(10)

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0      7    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     10    5  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     10    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3      7    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4      7    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
5      1    3  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0  ...         0   
6      1    1  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0  ...         0   
7      1    1  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0  ...         0   
8     11    5  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0  ...         0   
9     11    2  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   
5         0         0         0         0         0         0         0   
6         0         0         0         0         0         0         0   
7         0         0         0         0         0         0         0   
8         0         0         0         0         0         0         0   
9         0         0         0         0         0         0         0   

   monthsep  size_category  
0         0              1  
1         0              1  
2         0              1  
3         0              1  
4         0              1  
5         0              1  
6         0              1  
7         0              1  
8         1              1  
9         1              1  

[10 rows x 31 columns]

In [11]:
#Split the data
X=fire.iloc[:,:11]
Y=fire["size_category"]
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [12]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((361, 11), (361,), (156, 11), (156,))

In [13]:
#Grid Search CV
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [14]:
gsv.best_params_ , gsv.best_score_ 

({'C': 15, 'gamma': 50, 'kernel': 'rbf'}, 0.7451951951951952)

In [15]:
clf = SVC(C= 15, gamma = 50)
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 69.87179487179486


array([[  0,  47],
       [  0, 109]], dtype=int64)

In [16]:
clf1 = SVC(C= 15, gamma = 50)
clf1.fit(X , y)
y_pred = clf1.predict(X)
acc1 = accuracy_score(y, y_pred) * 100
print("Accuracy =", acc1)
confusion_matrix(y, y_pred)

Accuracy = 100.0


array([[139,   0],
       [  0, 378]], dtype=int64)

In [17]:
#POLY
clf2 = SVC(kernel= "poly") 
clf2.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred) 

Accuracy = 69.87179487179486


array([[  0,  47],
       [  0, 109]], dtype=int64)

In [18]:
clf2 = SVC()
param_grid = [{'kernel':['poly'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(C=15, gamma=50),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['poly']}])

In [19]:
gsv.best_params_ , gsv.best_score_

({'C': 15, 'gamma': 50, 'kernel': 'poly'}, 0.9586336336336336)