In [65]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score


In [66]:
#Import Dataset
sal_train=pd.read_csv('SalaryData_Train(1).csv')
sal_test=pd.read_csv('SalaryData_Test(1).csv')

In [67]:
sal_train.columns

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [68]:
sal_test.columns

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [69]:
string_col=['workclass','education','maritalstatus','occupation','relationship','race','sex','native']

In [70]:
#Preprocessing data
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
for i in string_col:
    sal_train[i]=label_encoder.fit_transform(sal_train[i])
    sal_test[i]=label_encoder.fit_transform(sal_test[i])

In [71]:
columns=list(sal_train.columns)
columns

['age',
 'workclass',
 'education',
 'educationno',
 'maritalstatus',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capitalgain',
 'capitalloss',
 'hoursperweek',
 'native',
 'Salary']

In [72]:
train_x=sal_train[columns[0:13]]
train_y=sal_train[columns[13]]

In [73]:
test_x=sal_test[columns[0:13]]
test_y=sal_test[columns[13]]

In [74]:
train_x=sal_train.iloc[0:500,0:13]
train_y=sal_train.iloc[0:500,13]

In [75]:
test_x=sal_test.iloc[0:300,0:13]
test_y=sal_test.iloc[0:300,13]

In [76]:
#SVM classification using kernels:linear, poly, rbf 
#KERNEL=LINEAR
from sklearn.svm import SVC


In [77]:
clf = SVC(kernel= "linear") 
clf.fit(train_x , train_y)
y_pred = clf.predict(test_x)
acc = accuracy_score(test_y, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(test_y, y_pred)    

Accuracy = 81.66666666666667


array([[218,  10],
       [ 45,  27]], dtype=int64)

In [78]:
#KERNEL=POLY
clf = SVC(kernel= "poly") 
clf.fit(train_x , train_y)
y_pred = clf.predict(test_x)
acc = accuracy_score(test_y, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(test_y, y_pred)  

Accuracy = 80.33333333333333


array([[227,   1],
       [ 58,  14]], dtype=int64)

In [79]:
#KERNEL=rbf
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(train_x,train_y)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [80]:
gsv.best_params_ , gsv.best_score_ 

({'C': 15, 'gamma': 0.5, 'kernel': 'rbf'}, 0.772)

In [81]:
clf = SVC(C= 15, gamma = 0.5) 
clf.fit(train_x , train_y)
y_pred = clf.predict(test_x)
acc = accuracy_score(test_y, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(test_y, y_pred)

Accuracy = 75.0


array([[225,   3],
       [ 72,   0]], dtype=int64)